---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deploy-7c752dfa
  labels:
    app: next-deploy-7c752dfa
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: next-deploy-7c752dfa
  template:
    metadata:
      labels:
        app: next-deploy-7c752dfa
    spec:
      serviceAccountName: ingress-manager
      containers:
        - name: next-deploy-7c752dfa
          image: docker.io/phengbunath/next-deploy-7c752dfa:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
