---
# Source: helm for kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: next-deploy-7c752dfa          # Service name
  labels:
    app: next-deploy-7c752dfa
spec:
  type: ClusterIP   # Service type (ClusterIP, NodePort, LoadBalancer)
  selector:
    app: next-deploy-7c752dfa         # Matches Deployment labels
  ports:
    - protocol: TCP
      port: 3000         # Service port
      targetPort: 3000  # Target container port
